version = 0.1
[default.deploy.parameters]
stack_name = "chime-iac-resume-stack"
resolve_s3 = true
s3_prefix = "chime-iac-resume-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[y.deploy.parameters]
stack_name = "chime-cloud-resume"
resolve_s3 = true
s3_prefix = "chime-cloud-resume"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
